export const FETCH_STAND_UP_MILESTONE = 'FETCH_STAND_UP_MILESTONE'
export const EDIT_STAND_UP_MILESTONE = 'EDIT_STAND_UP_MILESTONE'
export const UPDATE_ANSWERS_STAND_UP = 'UPDATE_ANSWERS_STAND_UP'
export const FINISHED_ASSESSTMENT_STAND_UP = 'FINISHED_ASSESSTMENT_STAND_UP'
export const UPDATE_NUM_MIL_STAND_UP = 'UPDATE_NUM_MIL_STAND_UP'


export const FETCH_SECURE_ATTACHMENT_MILESTONE = 'FETCH_SECURE_ATTACHMENT_MILESTONE'
export const EDIT_SECURE_ATTACHMENT_MILESTONE = 'EDIT_SECURE_ATTACHMENT_MILESTONE'
export const UPDATE_ANSWERS_SECURE_ATTACHMENT = 'UPDATE_ANSWERS_SECURE_ATTACHMENT'
export const FINISHED_ASSESSTMENT_SECURE_ATTACHMENT = 'FINISHED_ASSESSTMENT_SECURE_ATTACHMENT'
export const UPDATE_NUM_MIL_SECURE_ATTACHMENT = 'UPDATE_NUM_MIL_SECURE_ATTACHMENT'

export const SET_AREA_COLOR = 'SET_AREA_COLOR'
export const TOGGLE_AREA_COLOR = 'TOGGLE_AREA_COLOR'

export const SET_MILESTONE_COMPLETED = 'SET_MILESTONE_COMPLETED'

export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';