export const FETCH_SECURE_ATTACHMENT_MILESTONE = 'FETCH_SECURE_ATTACHMENT_MILESTONE'
export const FETCH_STAND_UP_MILESTONE = 'FETCH_STAND_UP_MILESTONE'
export const EDIT_STAND_UP_MILESTONE = 'EDIT_STAND_UP_MILESTONE'
export const EDIT_SECURE_ATTACHMENT_MILESTONE = 'EDIT_SECURE_ATTACHMENT_MILESTONE'